languageCode = "en"
languageName = "English"
weight = 1
title = "AI SYSTEMS TODAY"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  #logo = "img/662e95281b303_g.png"
  description = "A powerful, lightweight theme for Hugo."

[author]
  name = "Kyriakos Antoniadis"
  image = "img/662e95281b303_g.png"
  headline = "Empowering your business with cutting-edge AI solutions"
  bio = "AI SYSTEMS TODAY"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]