languageCode = "en"
languageName = "English"
weight = 1

title = "AI SYSTEMS TODAY"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "A powerful, lightweight theme for Hugo."
logo = "img/64w.png"
secondaryLogo = "img/64b.png"
# logoText = "AI SYSTEMS TODAY" # Add this line

[author]
#name = "Kyriakos Antoniadis"
#image = "img/662e95281b303_g.png"
# headline = "Empowering your business with cutting-edge AI solutions"
#bio = "AI SYSTEMS TODAY"
#links = [ 
#    { email = "mailto:contact@ai-systems.today" }, 
#    { github = "https://github.com/ai-systems-today" }, 
#    { linkedin = "https://www.linkedin.com/in/kyriacos-antoniades/" }, 
#    { medium = "https://medium.com/@ai-systems.today" }, 
#    { youtube = "https://www.youtube.com/channel/UCBwGhKFAzs_eNMw2mIxEY-Q" } 
#    ]


