# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Services"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 4

[[main]]
  name = "About"
  pageRef = "about"
  weight = 9

#[[main]]
#  name = "Shortcodes"
#  pageRef = "docs/shortcodes"
#  weight = 15

[[main]]
  name = "Tags"
  weight = 38

[[main]]
  name = "Cloud"
  parent = "Tags"
  pageRef = "keywords"
  weight = 1

[[main]]
  name = "Services"
  parent = "Tags"
  pageRef = "categories"
  weight = 2

[[main]]
  name = "Technologies"
  parent = "Tags"
  pageRef = "tags"
  weight = 3

[[main]]
  name = "Blog"
  pageRef = "guides"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "content"
  url = "https://calendly.com/contact-ai-systems-today/30min"
  weight = 45

#[[main]]
#  name = "Users"
#  pageRef = "users"
#  weight = 90

#[[main]]
#  name = "Merch"
#  url = "https://www.teepublic.com/user/blowfish-store/t-shirts"
#  weight = 100

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

#[[main]]
#  identifier = "twitter"
#  pre = "x-twitter"
#  url = "https://twitter.com/burufugu"
#  weight = 200

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

#[[main]]
#  identifier = "github"
#  pre = "github"
#  url = "https://github.com/nunocoracao/blowfish"
#  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Technologies"
   pageRef = "tags"
   weight = 12

[[footer]]
   name = "Services"
   pageRef = "categories"
   weight = 11

[[footer]]
   name = "Cloud"
   pageRef = "keywords"
   weight = 10

 #[[footer]]
 #  name = "Authors"
 #  pageRef = "authors"
 #  weight = 20
